/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2008 Sun Microsystems, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Sun designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Sun in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s): Tim Boudreau
 *
 * Portions Copyrighted 2008 Sun Microsystems, Inc.
 */
package syntaxtreenavigator;

import com.sun.source.tree.*;
import com.sun.tools.javac.api.*;

import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import javax.swing.tree.*;
import javax.tools.*;
import java.awt.*;
import java.io.*;
import java.util.*;
import java.util.prefs.*;

/**
 *
 * @author  Tim Boudreau
 */
public class SyntaxTreeVisualizer extends javax.swing.JFrame implements Runnable, DiagnosticListener {
    JFileChooser jfc = new JFileChooser();
    SyntaxTreePanel pnl = new SyntaxTreePanel();

    /** Creates new form SyntaxTreeVisualizer */
    public SyntaxTreeVisualizer() {
        setTitle ("Syntax Tree Visualizer");
        initComponents();
        CellRendererPane pane = new CellRendererPane();
        pane.add (jfc);
        pane.doLayout();
        add (pnl, BorderLayout.CENTER);
        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        if (compiler == null) {
            JOptionPane.showMessageDialog(null,
                "<html><center>ToolProvider.getSystemJavaCompiler() returned " +
                "null.<br>Either javac is not on the classpath, or it is not<br>" +
                "Sun's implementation of javac and the compiler classes are <br>" +
                "present but not implemented");
            System.exit(1);
        }
    }

    @Override
    public void addNotify() {
        super.addNotify();
        EventQueue.invokeLater(this);
    }

    public void run() {
        super.setState(Frame.MAXIMIZED_BOTH);
        openMenuItemActionPerformed(null);
    }

    private static final class FF extends FileFilter {
        public boolean accept(File f) {
            return f.isDirectory() || f.getName().endsWith(".java");
        }

        public String getDescription() {
            return "Java Source Files";
        }
    }
    static final FF ff = new FF();
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setMnemonic('O');
        openMenuItem.setText("Open...");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    File lastDir = null;

    private File getLastDir() {
        if (lastDir == null) {
            String fname = Preferences.userNodeForPackage(SyntaxTreeVisualizer.class).get("dir", null);
            if (fname == null) {
                fname = System.getProperty ("user.home");
            }
            if (fname != null) {
                lastDir = new File (fname); //NOI18N
                if (!lastDir.exists() || !lastDir.isDirectory()) {
                    lastDir = null;
                }
            }
        }
        return lastDir;
    }

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        jfc.setFileHidingEnabled(true);
        jfc.setFileFilter(ff);
        File previousDir = getLastDir();
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (previousDir != null) {
            jfc.setCurrentDirectory(previousDir);
        }
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File dir = jfc.getSelectedFile().getParentFile();
            if (!dir.equals(previousDir)) {
                setLastDir (dir);
            }
            try {
                pnl.setStatusText ("Opening " + jfc.getSelectedFile().getName());
                openFile (jfc.getSelectedFile());
                lastFile = jfc.getSelectedFile();
                pnl.setStatusText ("Opened " + jfc.getSelectedFile().getName());
                pnl.expandPath(new TreePath(pnl.getTree().getModel().getRoot()));
                setTitle ("Syntax Tree Visualizer - " + lastFile.getName());
                pack();
            } catch (IOException ioe) {
                ioe.printStackTrace();
                JOptionPane.showMessageDialog(this, ioe.getLocalizedMessage());
            }
        }
    }//GEN-LAST:event_openMenuItemActionPerformed


    private File lastFile = null;
    private void setLastDir (File dir) {
        Preferences.userNodeForPackage(SyntaxTreeVisualizer.class).put("dir", dir.getPath()); //NOI18N
        lastDir = dir;
    }

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit (0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    void openFile (File file) throws IOException {
        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();

        StandardJavaFileManager m = compiler.getStandardFileManager(this, null,
                null);
        Iterable <? extends JavaFileObject> toCompile =
                m.getJavaFileObjects(file);
        Iterable <? extends File> outdir =
                Collections.singleton(new File(
                System.getProperty("java.io.tmpdir"))); //NOI18N
        m.setLocation(StandardLocation.CLASS_OUTPUT, outdir);
        JavacTaskImpl task = (JavacTaskImpl) compiler.getTask(null,
                m, null, null, null, toCompile);

        Iterator <? extends CompilationUnitTree> it = task.parse().iterator();
        pnl.init (it);
        pnl.getFilenameLabel().setText(file.getPath());
    }

    public void report(Diagnostic diagnostic) {
        pnl.report (diagnostic);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem openMenuItem;
    // End of variables declaration//GEN-END:variables

}
