# 1:20 pm 6/4/97

all: backyard medbook topic \
	organism person \
	brain sense identify

%$0: %.ku
	ke $*.ku $*.out $*.err $*.log
	more $*.out $*.err $*.log

%$0: %.cu
	ke $*.cu $*.out $*.err $*.log
	more $*.out $*.err $*.log
